services:
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Port=5432;Database=salesdb;Username=postgres;Password=postgres;Include Error Detail=true 
    ports:
      - 5000:8080
      - 5001:8081
    volumes:
      - ./AppData/UserSecrets:/home/app/.microsoft/usersecrets:ro

  postgres:
    ports:
      - 5432:5432
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=salesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DbScripts:/dbscripts
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@exemplo.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  pgadmin_data: